### ISSUE TITLE
opinion: temporary should go to TMPDIR, explicit path for "valuable" data, study dir? 

### ISSUE THREAD

**Issue by yarikoptic** [SpikeInterface/spikesorters#131]
With the help on other issues (thanks @alejoe91 and @samuelgarcia) the dummy user progressed to the point of actually running a spike sorting! whoohoo.  

While running it I spotted:
```
> ss.run_klusta(recording)
RUNNING SHELL SCRIPT: /home/yoh/proj/dandi/mvdm/tmp_klusta/klusta.sh
``` 
and similarly to my whining about `.json` representations of extractors being dumped into current directory (which might have nothing to do with spike interfaces, or not even be writeable), I would like to bring up a discussion here about creating temporary directories in current path.  If it is a truly temporary directory -- it should just be created in an appropriate to any temporary directory location, and ideally removed after.  May be in some cases it is desired (data locality? obsession?) to have temporary stuff around - that is where some configuration setting could be allowed to augment it (but typically it is done by setting `TMPDIR` env variable).

In this case it feels that it is not really a "temporary directory" -- it is a processing/results directory.  There is an `output_folder` parameter I could have used to explicitly specify it. It feels that current directory is assumed to be some kind of a "study folder", where all stuff should go to.  But then IMHO it should be somehow explicitly specified or at least user to be informed that all outputs will be dumped into "study folder" which is "." .  And then path above, which isn't really a `tmp` path, should may be reflect that, e.g. be `si-outputs/klusta`.

Just thought to share. Cheers!

**Comment by samuelgarcia** [comment]
Yes, this folder is not excatly a tmp folder, it is an output folder.
It can be seen as an tmp folder if use the delete_output_folder=True.

I prefer the ```klusta_output``` also.

I like the idea of this folder to be just here in the current firectory so a begininer can understand the fact that there is a output_folder rapidly. /tmp would be a bad idea because it could grow rapidly and on some computing cluster the /tmp is a by node folder wheras the current folder is often a share folder.
