### ISSUE TITLE
Error With Wave_clus - Upgrading spikesorters 

### ISSUE THREAD

**Issue by Bilalgp** [SpikeInterface/spikesorters#140]
I am having trouble with wave_clus similar to the issue in this thread:

https://github.com/SpikeInterface/spikesorters/issues/87

I tried installing the upgrade to spikesorters but I got the following error. It installs, but if I try running any import function (say from spiketutorial) the import fails. I tried updating spikeinterface but when doing so, it downgraded spikesorters to 0.2.0. 

![image](https://user-images.githubusercontent.com/26805330/81470674-f7c3c100-91b9-11ea-8f31-b53d1d7b690b.png)

**Comment by alejoe91** [comment]
This is due to SpikeInterface pointing to previous versions. We are making a new release before Tuesday with the updated versions. 

For the moment, what you should do is:

- install SpikeInterface
- upgrade the single packages
- do NOT upgrade spikeinterface, otherwise it will downgrade again the other packages

**Comment by Bilalgp** [comment]
![image](https://user-images.githubusercontent.com/26805330/81489696-9138b480-9246-11ea-8b35-4f6446481335.png)

I get this error if I keep spikesorters updated when trying to import the packages. I am using the jupyter spiketutorial notebook file.

**Comment by Bilalgp** [comment]
I see the other packages weren't updated properly.
