### ISSUE TITLE
Q: spike sorters for thresholded spikes (in NeuraLynx .ntt files)?

### ISSUE THREAD

**Issue by yarikoptic** [SpikeInterface/spikesorters#147]
In the dataset I had mentioned before (http://datasets.datalad.org/?dir=/labs/mvdm/MotivationalT-v2/R050/R050-2014-03-31_raw; see e.g. https://github.com/SpikeInterface/spikeextractors/issues/364) we have .ntt files (a file for 14 out of 16 tetrodes) which have data for time windows (8 samples before 24 after) around detected spikes, typically a few 100k windows per tetrode.  Then there are also .ncs files which are low-pass filtered and downsampled, so SHOULD NOT be used for spike sorting (and that is why probably those spike sorting results I previously shown were crap). 

So if we "load" the data using the extractor total summary is
```
NeuralynxIO: data/MotivationalT-v2/R050/R050-2014-03-31_raw
nb_block: 1
nb_segment:  [3]
signal_channels: [CSC33, CSC41, CSC45, CSC50 ... HS1R1 HS1R2 HS3R1 HS3R2]
unit_channels: [chTT1#64#0, chTT1#65#0, chTT1#66#0, chTT1#67#0 ... chTT16#28#0 chTT16#29#0 chTT16#30#0 chTT16#31#0]
event_channels: [Events event_id=11 ttl=0, Events event_id=11 ttl=4, Events event_id=11 ttl=32, Events event_id=11 ttl=64, Events event_id=11 ttl=128]
```
In our (with @manimoh) exploration of spikeinterfaces to get this data sorted we got a little bit stuck due to following issues (sorry for clamping them into one "use case issue" ;)):

## Unable to load (just) .ntt files

- if we use `se.NeuralynxRecordingExtractor` to load data from a directory in which we keep **only** .ntt files - it blows with 
```
~/anaconda-5.2.0-2.7/envs/mvdm-nept/lib/python3.7/site-packages/spikeextractors/extractors/neoextractors/neobaseextractor.py in __init__(self, **kargs)
     54         # in neo one channel group have the same dtype/sampling_rate/group_id
     55         num_chan_group = len(self.neo_reader.get_group_channel_indexes())
---> 56         assert num_chan_group == 1, 'This file have several channel groups spikeextractors support only one groups'
     57 
     58         # spikeextractor for units to be uV implicitly

AssertionError: This file have several channel groups spikeextractors support only one groups
```
due to the fact that `num_chan_group` is actually 0 (not `>1`, please add actual number to the assertion message)

## Spike sorters seems to try to load LFP data

As via `.get_traces()` in https://github.com/SpikeInterface/spikeextractors/blob/34aba7ae4dcebf50356ea2158a899295a1f1e10f/spikeextractors/extraction_tools.py#L308 . 

So the ultimate question is - how to make spikeinterfaces work with thresholded spikes recorded in .ntt files?

**Comment by alejoe91** [comment]
Hi @yarikoptic 

Unfortunately at the moment this is not possible because all sorters work on the full recording :( in principle some of the density-based sorters should work for waveforms only..but it would be tricky to support that as the RecordingExtractor itself expects a continuous signal (get_traces())

Do you have access to the raw data?

**Comment by yarikoptic** [comment]
That datalad is the raw data as far as I know, spit out by neutrality neuralynx system. Do we have continuous recording at 33kHz sampling rate - nope. If sorters don't impose any additional filtering (do they?) we could probably come up with continuous data fill of 0s where there is no data within .ntt files (or just pretty much ignore those periods) and set thresholds and windows to match what is in ntt files... But that sounds too ad hoc to be right. So it seems to be the matter that some sorters interfaces could be adjusted/parameterized to consume already windowed spike timeseries. Uniquely our use case that unique.

**Comment by alejoe91** [comment]
@yarikoptic some sorters do impose additional filtering. I think that the field is moving towards using raw data as input, also because storage solutions are not as limited as before, which required to only save above-threshold snippets. 

I agree that sorting already cut waveforms could be beneficial, and probably klusta and wave-clus could be *hacked* to only run the clustering part (provided that waveforms are aligned).

One way this could be used in SI is by providing some clustering algos in the `spiketoolkit.sortingcomponents` submodules, which at the moment only has a detection function. 

In general, do you know if it's at least possible to save raw data with the Neuralynx system?

**Comment by samuelgarcia** [comment]
@yarikoptic : neo API (for historical reason) have this "waveform read" ability.
Spikeinterface don't.
I don't think that many user still use this. We left it but it is a pain to maintain.

This explain this num_chan_group=0 with your file.
Spikeinterface only retrieve traces and spike times.
neo can also do event, epoch and waveforms.
In case, of a file that have only waveforms then it is an empty file from spikeinterface referencial.


This spike sorting "waveforms cut" way is a bad pratice that almost all lab left (I hope so):
  * bad waveform alignement (some time on threhold itself!!) --> more noise on PCA
  * very often bad filtering (forward only)
  * no noise estimation possible
  * very often bad threshold because quite low 
  * very often the engine than cut waveform take the first incomers even if a better peak is following.
  * no collision resolution
  * useless in high channels counts (>4) because it is a sparse spatial information
  * sometimes leads to very big and non efficient files (slow to parse)

spike2, neurralynx, blackrock and plexon hinerits this features from the past but this is "bad pratice".

**Comment by yarikoptic** [comment]
> In general, do you know if it's at least possible to save raw data with the Neuralynx system?

May be @manimoh or @mvdm could clarify on that, I have no clue.  I bet it is possible.

We were trying to sort this data because it is a historical dataset which originally was "manually sorted" based on the properties of those waveforms.  The idea was to see which sorting algorithm would provide best agreement with manual sorting.  

But it feels that 

- in the short run we could try to run sorters manually tuning their options to avoid filtering etc
- in the longer run - switch to another dataset for which full continuous raw data recording is available.

A few final cents: 

On the spikeinterfaces side it would be great to see

- at least a warning whenever it reads/sorts a highly downsampled data which should not be sorted (.ncs files were at 2k sampling rate)
- asserts like in the original post to include actual values which  "fail" the assertion

On neo side for NeuraLynxIO 

- I do see benefits from being able to read all files from a directory, but as in my case here, it would be great if  I could just point to the file(s) of interest, thus making it less ambiguous on what data I am actually analysing.

**Comment by manimoh** [comment]
> In general, do you know if it's at least possible to save raw data with the Neuralynx system?

It is possible to do that in Neuralynx, and that's what we plan on doing moving forward.

**Comment by samuelgarcia** [comment]
I anderstand. I you want to compare to this manual sorting you don't need waveform, only spiek tims. spikecomparison is your firend because it match 2 datasets (on manual in your case and one auto). have look here https://spikeinterface.readthedocs.io/en/latest/modules/#comparison-tutorials

Yes good idea, we could filter channel <10kHz and not expose then on spiekinterface side.

On the neo side, we have a lazy load system so nothing is loaded and everything is loadable. This is why the entire folder is exposed. I think for some IO we have option to not expose then at all, for instance waveforms.
See this https://neo.readthedocs.io/en/0.8.0/rawio.html

**Comment by yarikoptic** [comment]
> spikecomparison is your firend because it match 2 datasets (on manual in your case and one auto).

but if I got it right - we do not have "auto". We only have detected spikes and waveforms (for each tetrode).  That is what we wanted to run some automated sorting on.

**Comment by samuelgarcia** [comment]
Ah ok.
I am lost sorry. You want auto on the waveform extracted.
I think you could make your own "auto sorter" with: SVD (or PCA) (=sklearn easy for you) + hdbscan (very nearby sklearn) you should have pretty good result for 4 lines of codes.

**Comment by yarikoptic** [comment]
> You want auto on the waveform extracted.

yeap

> I think you could make your own "auto sorter" with:

nah, no "own".  Let me extend (added clarifications in **bold**): "The idea was to see which **existing** sorting algorithm would provide best agreement with manual sorting, **to decide on which one to use in the future**".

**Comment by alejoe91** [comment]
I think that most of the currently available sorters (at least the template-matching ones) cannot be used in that case :(

**Comment by yarikoptic** [comment]
Thank you @alejoe91 and @samuelgarcia for the feedback and information!  I guess nothing to do about this issue (besides [a few points mentioned above](https://github.com/SpikeInterface/spikesorters/issues/147#issuecomment-634687981) I leave at your discretion to file/address), so closing.
