### ISSUE TITLE
Separating _setup_recording and _run when with sorter [advice]

### ISSUE THREAD

**Issue by timsainb** [SpikeInterface/spikesorters#220]
I'm trying to figure out how to optimize my pipeline to run sorts on a compute cluster. At present I'm submitting sort jobs to the cluster, which runs a python script pointing spikeinterface at my binary data and calling `run_sorter`. There are basically two things that take time.

1) `_setup_recording`, grabbing data, getting it in the right format, applying preprocessors. This is basically limited by IO/read/write speeds, and doesn't make use of the GPU or most of the CPU cores on the nodes. Potentially, this can be run across multiple sorts in parallel, and probably shouldn't waste valuable cluster nodes on copying files. 
2) `_run` running the actual sort. This should make full use of the compute node. 

This is a optimal because a lot of time on these compute nodes is wasted copying/preprocessing, which doesn't make full use of the node. 

It seems to me like I should be making this a two step process to optimize cluster usage: First, on the head node of the cluster run a bunch of _setup_recording's in parallel. Then when the recording is setup, pickle the Sorter object. Then, submit a bunch of jobs to the cluster, loading the pickled sorter object, and calling _run directly, pointed where the recording was formatted/ set up. 

Does that seem reasonable? Is there a better way to separate out these two steps?

**Comment by samuelgarcia** [comment]
Hi Tim,
the behavior you would like is already available in the "new APi" of spikeinterface (next release).
Have a look here:
https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/sorters/runsorter.py#L48

In short the new BaseSorter have only classmethod.
So there is no more instance.
All the state are store in the sorter folder. (recording/params/logs)
This is very convinient for job schedulding because you only need the folder for each steps.

Also, note that there are already some job launcher in spikeintyerface already.
See this : https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/sorters/launcher.py

So even, if the next release is not stable yet because of big refactoring and a non backward compatible API, you should go for this new version.
You need to install spikeinterface from source at the moment.
You would a advance beta tester which would be very usefull for us.

Sam

**Comment by timsainb** [comment]
Thanks @samuelgarcia ! I'll switch over to the master branch here in a new environment and rewrite my pipeline to use the refactored api. 

Would you be able to point me toward, or provide some sudocode for, initializing the folder in on script, then running the sort in another script? 

Something like this?

Script 1:
```python
from spikeinterface.sorters.sorterlist import sorter_dict
import spikeinterface.extractors as se
import pickle 

# create recording...
recording = se.NumpyRecording(...)

# create sorter
SorterClass = sorter_dict[sorter_name]

# initialize sort
output_folder = SorterClass.initialize_folder(recording, output_folder, verbose, remove_existing_folder=True)
SorterClass.set_params_to_folder(recording, output_folder, sorter_params, verbose)
SorterClass.setup_recording(recording, output_folder, verbose=verbose)

# with open('mysorter.pickle', 'wb') as fp:
   pickle.dump(SorterClass, fp)
```

Script 2:
```python
import pickle

with open('mysorter.pickle', 'rb') as fp:
    SorterClass = pickle.load(fp)

SorterClass.run_from_folder(output_folder, raise_error, verbose)
sorting = SorterClass.get_result_from_folder(output_folder)

# save sort output
...
```

**Comment by timsainb** [comment]
Looking through the new api, I'm realizing now that there are some major changes that are going to require a significant amount of time to deal with in my pipeline, and the documentation's not there yet. Is there a any roadmap (even an informal one) to help with finding where things are being moved? And is there anything that hasn't been implemented yet in the new version that exists in the old version that I'll be running into down the line? 

After a few mins of playing around with the new code, SubRecordingExtractor is gone, which is replaced by ChannelSliceRecording for segmenting channels, but presumably there's another new class for segmenting frames? I can't find it.

**Comment by samuelgarcia** [comment]
Hi Tim.
Comment about your first question:
 1. This is the main idea 
 2. youd should not use pickle.
 3. The only thing you have to "pickle" is sorter_name and folder.

So
```python
from spirkinterface.sorters..sorterlist import sorter_dict

recording = ...
sorter_name = 'kilosort'
folder = '/path/to/sorter
sorter_params = {} # use default


# step one: prepare

output_folder = SorterClass.initialize_folder(recording, folder, verbose, remove_existing_folder)
SorterClass.set_params_to_folder(recording, output_folder, sorter_params, verbose)
SorterClass.setup_recording(recording, output_folder, verbose=verbose)

# step 2 : run sorter
SorterClass = sorter_dict[sorter_name]
SorterClass.run_from_folder(output_folder, raise_error, verbose)

# step 3 : retrieve result
SorterClass = sorter_dict[sorter_name]
sorting = SorterClass.get_result_from_folder(output_folder)
```


For your second comment, yes it will break your code and need some adaptation.
But keep it mind that some stuffs are really faster (include copy files) and have a better internal design.
The doc is already here: https://spikeinterface.readthedocs.io/en/latest/

Also have a look to [this](https://spikeinterface.github.io/blog/quick-benchmarck-with-new-api-and-new-sorters-april-2021/)

Yes:  ChannelSliceRecording/AppendSegmentRecording/ConcatenateSegmentRecording are totally new stuff.
They are the main change for a user perscpective. It is a apin but it go toward the go direction.

Segmenting frame is not done yet, it is is in my todo list.
If it is urgent for you, I can try to implement very soon.
(It is a bit more complicated because we handle multi segment now).

Another big change is the waveform_extractor.

Consider the actual master as very near to the next release in term of API.
Some stuff are not done yet but the internal API won't change a lot now.
My estimation is 90% of the "porting" is done.
My personal plan is to release in July 2021 but I am not alone in the team and some member would prefer september.
Lets see.
The release timeline also depend on beta tester :)

**Comment by timsainb** [comment]
Lots of really exciting updates. I'll give it a go. Let me know if you end up having any questions from the user end. 

> Segmenting frame is not done yet, it is is in my todo list.
> If it is urgent for you, I can try to implement very soon.

That would be very appreciated. If I'm going to use the new codebase this is a necessity for me.

Thanks!

**Comment by timsainb** [comment]
Re-the code you provided, I'm looking through the run_sorter/run_from_folder function, and I see that there is some plan to implement a flag to delete the sort folder after sorting. Presumably, we want to hold onto the sort data which should be pretty small, but not the reformatted recording data. Is that the plan for this flag?

> ```python

> # step 2 : run sorter
> SorterClass = sorter_dict[sorter_name]
> SorterClass.run_from_folder(output_folder, raise_error, verbose)
> 
> # step 3 : retrieve result
> SorterClass = sorter_dict[sorter_name]
> sorting = SorterClass.get_result_from_folder(output_folder)
> 
> ```

 Alternatively, it would make sense to, after sorting, have a function to re-save just the sort data elsewhere? e.g.

1. create temp directory 
2. run sort from temp directory
3.  **save sort data elsewhere** (e.g. sort.save('my/data/directory/'))
4. delete temp folder

**Comment by samuelgarcia** [comment]
Note that you can also control the place with 
`sorting = run_sorter(recording, output_folder='/my/favorite/path')`
