### ISSUE TITLE
Chunking required for SSMdaRecordingExtractor and write_to_binary_dat_format

### ISSUE THREAD

**Issue by mhhennig** [SpikeInterface/spikesorters#92]
Some sorters use the internal `SSMdaRecordingExtractor` or `write_to_binary_dat_format` to write out raw data for sorting. There is no chunking, the whole raw data is read in one go. This causes memory errors.

Sorters affected are Ironclust and Kilosort2 (maybe others?)

**Comment by alejoe91** [comment]
I think we could add in `write_to_binary_dat_format` an automatic chunking based on available RAM. Should not take too much!

For the `SSMdaRecordingExtractor` we could do something similar (maybe @magland has some code already). Or we could convert the sorters that use `SSMdaRecordingExtractor` to use a dat file. In the long run I vote for the latter option.

**Comment by samuelgarcia** [comment]
write_to_binary_dat_format have a **chunk_size** kargs.
I implemented it.
It was for KS, KS2, klusta and TDC.
It has disappear for KS and KS2 but I don't known when. 
We need to check the history.

**Comment by alejoe91** [comment]
Hi @jamesjun 

We are experiencing memory issues with the ironclust wrapper when sorting large datasets as the SSMdaRecordingExtractor attempts to write the entire dataset at once (and in doing so to load it in memory): https://github.com/SpikeInterface/spikesorters/blob/master/spikesorters/ironclust/ironclust.py#L130

In spikeextractors, we have a [write binary function](https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extraction_tools.py#L255) that supports chunking. Would it be possible to update the `p_ironclust` to load the binary file directly instead of the mda file? We could write all metadata to the argfile. 

What do you think?

**Comment by jamesjun** [comment]
Ironclust can directly load from MDA format. Please refer to the spikeforest2 wrapper on how I implemented it. 

-James

**Comment by mhhennig** [comment]
> Ironclust can directly load from MDA format. Please refer to the spikeforest2 wrapper on how I implemented it.

Hi @jamesjun 

This has the same problem, it'd not chunked. On line 105 in

https://github.com/flatironinstitute/spikeforest2/blob/555e9057111c52da826bf4ad559ddef3d9a57c51/spikeforest2_utils/autoextractors/mdaextractors/mdaextractors.py#L97

you just use `raw = recording.get_traces()`. For a large file (like the one I have, 220GB) this will not fit in memory.

Does Ironclust only read mda?

**Comment by alejoe91** [comment]
I think that we could do 2 things here:

1. have ironcludt load binary data directly
2. add chunking to the SSMdaRecordingExtractor / MdaRecordingExtractor

I think that solution 2 is probably the most straightforward. Do you guys agree?

**Comment by jamesjun** [comment]
IronClust can load binary files natively but the autoextractor converts to mda format. we need to bypass that. Internally ironclust processes in chunks of half a gigabyte in memory in float32 format. i will have a look how to bypass autoextractor if the format is already in binary.  

-James

**Comment by alejoe91** [comment]
Changed the write mechanism of the basic MdaRecordingExtractor. Now both IC and WC use the extractor from SE.

See:
https://github.com/SpikeInterface/spikesorters/pull/106

and
https://github.com/SpikeInterface/spikeextractors/pull/325
